### ISSUE TITLE
Pillow won't install

### ISSUE THREAD

**Issue by derbengale** [fabianonline/OctoPrint-Telegram#161]
Hello everyone,
I just tried to install the Telegram plugin on my new Octoprint setup. Its running on the latest DietPi Distro. Octoprint was installed with the Distros built-in compilation script if that plays a role. I got the same issue like @robro1 in issue #79. The output was the following:
```
 running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0z2y69/pillow/setup.py", line 812, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html



    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0z2y69/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wUQTYB/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-0z2y69/pillow/
```
I figured out this must be because zlib is required  to install pillow, which is a requirement for the Telegram plugin, so I tried to install it with 
`apt-get install zlib`
but with no luck. There doesnt seem to be a package.
`pip install zlib ` also didn't work 

Does someone have a clue how I can fix this to make the Telegram plugin work?

**Comment by derbengale** [comment]
Allright. I figured it out.

I downloaded zlib at [this](http://www.zlib.net/) website and unpacked it on my pi.
In the zlib folder you have to run the following commands:
```
chmod +x configure
./configure
make
make install
```
after that, the Telegram plugin installs like a charm.
This can be closed
