### ISSUE TITLE
Cannot install telegram plugin

### ISSUE THREAD

**Issue by OliverWieland** [fabianonline/OctoPrint-Telegram#170]
After I updated my raspian from jessy to stretch (new installation), I can't install this plugin. Below is the output of the plugin manager

```
Installiere Plugin...
Installiere Plugin "OctoPrint-Telegram" von https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip...
/home/pi/OctoPrint/venv/bin/python2 -m pip install https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip --no-cache-dir
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip
Downloading https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip
Requirement already satisfied: OctoPrint in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint-Telegram==1.4.2) (1.3.10)
Collecting pillow (from OctoPrint-Telegram==1.4.2)
Downloading https://files.pythonhosted.org/packages/81/1a/6b2971adc1bca55b9a53ed1efa372acff7e8b9913982a396f3fa046efaf8/Pillow-6.0.0.tar.gz (29.5MB)
Requirement already satisfied: watchdog<0.9,>=0.8.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.8.3)
Requirement already satisfied: python-dateutil<2.7,>=2.6.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.1)
Requirement already satisfied: feedparser<5.3,>=5.2.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (5.2.1)
Requirement already satisfied: requests<3,>=2.18.4 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.21.0)
Requirement already satisfied: chainmap<1.1,>=1.0.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.0.3)
Requirement already satisfied: flask<0.11,>=0.10.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10.1)
Requirement already satisfied: scandir<1.4,>=1.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)
Requirement already satisfied: monotonic<1.4,>=1.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)
Requirement already satisfied: frozendict<1.3,>=1.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.2)
Requirement already satisfied: Jinja2<2.9,>=2.8.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.8.1)
Requirement already satisfied: emoji<0.5,>=0.4.5 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.5)
Requirement already satisfied: netifaces<0.11,>=0.10.6 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10.9)
Requirement already satisfied: Flask-Babel<0.10,>=0.9 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.9)
Requirement already satisfied: pkginfo<1.5,>=1.4.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.4.2)
Requirement already satisfied: markdown<2.7,>=2.6.9 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.11)
Requirement already satisfied: pyserial<3.5,>=3.4 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.4)
Requirement already satisfied: semantic-version<2.5,>=2.4.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.4.2)
Requirement already satisfied: werkzeug<0.9,>=0.8.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.8.3)
Requirement already satisfied: websocket-client<0.41,>=0.40.0 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.40.0)
Requirement already satisfied: psutil<5.5,>=5.4.6 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (5.4.8)
Requirement already satisfied: awesome-slugify<1.7,>=1.6.5 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.6.5)
Requirement already satisfied: Flask-Login<0.3,>=0.2.11 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.2.11)
Requirement already satisfied: Flask-Principal<0.4,>=0.3.5 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.3.5)
Requirement already satisfied: sarge==0.1.5post0 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.1.5.post0)
Requirement already satisfied: pylru<1.1,>=1.0.9 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.0.9)
Requirement already satisfied: Flask-Assets<0.11,>=0.10 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10)
Requirement already satisfied: netaddr<0.8,>=0.7.19 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.7.19)
Requirement already satisfied: future<0.16,>=0.15.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.15.2)
Requirement already satisfied: Click<6.3,>=6.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (6.2)
Requirement already satisfied: regex!=2018.11.6 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2019.4.12)
Requirement already satisfied: wrapt<1.11,>=1.10.11 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.10.11)
Requirement already satisfied: futures<3.2,>=3.1.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.1.1)
Requirement already satisfied: PyYAML<3.11,>=3.10 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.10)
Requirement already satisfied: tornado==4.5.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (4.5.3)
Requirement already satisfied: rsa<3.3,>=3.2.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.2.3)
Requirement already satisfied: argh>=0.24.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.1.2)
Requirement already satisfied: six>=1.5 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from python-dateutil<2.7,>=2.6.1->OctoPrint->OctoPrint-Telegram==1.4.2) (1.12.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (2019.3.9)
Requirement already satisfied: itsdangerous>=0.21 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from flask<0.11,>=0.10.1->OctoPrint->OctoPrint-Telegram==1.4.2) (1.1.0)
Requirement already satisfied: MarkupSafe in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from Jinja2<2.9,>=2.8.1->OctoPrint->OctoPrint-Telegram==1.4.2) (1.1.1)
Requirement already satisfied: Babel>=1.0 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.0)
Requirement already satisfied: speaklater>=1.2 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)
Requirement already satisfied: Unidecode<0.05,>=0.04.14 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.21)
Requirement already satisfied: blinker in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Principal<0.4,>=0.3.5->OctoPrint->OctoPrint-Telegram==1.4.2) (1.4)
Requirement already satisfied: webassets>=0.10 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Assets<0.11,>=0.10->OctoPrint->OctoPrint-Telegram==1.4.2) (0.12.1)
Requirement already satisfied: singledispatch in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-Telegram==1.4.2) (3.4.0.3)
Requirement already satisfied: backports-abc>=0.4 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.5)
Requirement already satisfied: pyasn1>=0.1.3 in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from rsa<3.3,>=3.2.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.5)
Requirement already satisfied: pytz>=0a in /home/pi/OctoPrint/venv/lib/python2.7/site-packages (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (2019.1)
Installing collected packages: pillow, OctoPrint-Telegram
Running setup.py install for pillow: started
Command "/home/pi/OctoPrint/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-BusFVZ/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wlQ01d/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/OctoPrint/venv/include/site/python2.7/pillow" failed with error code 1 in /tmp/pip-install-BusFVZ/pillow/
Running setup.py install for pillow: finished with status 'error'
Complete output from command /home/pi/OctoPrint/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-BusFVZ/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wlQ01d/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/OctoPrint/venv/include/site/python2.7/pillow:
running install
running build
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/PIL
copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/_version.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
running egg_info
writing src/Pillow.egg-info/PKG-INFO
writing top-level names to src/Pillow.egg-info/top_level.txt
writing dependency_links to src/Pillow.egg-info/dependency_links.txt
reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.c'
warning: no files found matching '*.h'
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.appveyor.yml'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.codecov.yml'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching '.readthedocs.yml'
warning: no previously-included files found matching 'azure-pipelines.yml'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
no previously-included directories found matching '.azure-pipelines'
no previously-included directories found matching '.travis'
writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
running build_ext
The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.
Please see the install instructions at:
https://pillow.readthedocs.io/en/latest/installation.html
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-BusFVZ/pillow/setup.py", line 804, in <module>
raise RequiredDependencyException(msg)
__main__.RequiredDependencyException:
The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.
Please see the install instructions at:
https://pillow.readthedocs.io/en/latest/installation.html
----------------------------------------
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Fehler!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output
```

**Comment by OliverWieland** [comment]
Okay, I made it...
I had to install libjpeg-dev. After that, It worked fine...
