### ISSUE TITLE
Upgrade in octoprint interface fails

### ISSUE THREAD

**Issue by hieronymousch** [fabianonline/OctoPrint-Telegram#23]
Popup shows that update is available. Click on update, get error message that update fails.

Octolog shows this error;
2016-05-17 19:29:08,873 - octoprint.plugins.softwareupdate - INFO - Starting update of telegram to 1.3.0...
2016-05-17 19:29:08,935 - octoprint.plugins.softwareupdate - ERROR - Update of telegram can not be performed
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.11-py2.7.egg/octoprint/plugins/softwareupdate/__init__.py", line 637, in _perform_update
    update_result = updater.perform_update(target, check, target_version)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.11-py2.7.egg/octoprint/plugins/softwareupdate/updaters/pip.py", line 50, in perform_update
    install_arg = check["pip"].format(target_version=target_version)
KeyError: 'target'

**Comment by derpicknicker1** [comment]
It is an issue in the old (1.2.1) version where a variable is named 'target' instead of 'target_version'. So there is no way to fix that for us. The new version will handle updates correct. To update do one of the following steps:

* Uninstall your 1.2.1 plugin version from octoprint via plugin manager. Then reinstall the new version via plugin mamager. Your settings schuld be safe i think (i dont know exactli, don't tested)

* Go to the releases page of this project, download v1.3.0.zip. Then go to OctoPrints Pluginmamager and click on "more". At the bottom of the opened dialog you will find a filed where you can choose the zip file for upload. So choose the file and hit install. Done.

* find your __init__.py of the telegram plugin in your OctoPrint installation. Search for the method get_update_information. In this Method you will find a URL-string with {target} in it. Change it to {target_version} . Now restart octoprint. Update should work now.
