### ISSUE TITLE
Plugin not Loading: undefined symbol: xcb_xc_oisc_id

### ISSUE THREAD

**Issue by mkrasselt1** [fabianonline/OctoPrint-Telegram#401]
I Noticed the plugin beeing gone on my machine some time ago, and now started to investigate.
Turns out its requiring as symbol from a image librarry, that no longer exists?
`2022-03-29 21:38:10,356 - octoprint.plugin.core - ERROR - Error loading plugin telegram
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1291, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 68, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_telegram/__init__.py", line 2, in <module>
    from PIL import Image
  File "/home/pi/oprint/lib/python3.7/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: /usr/lib/arm-linux-gnueabihf/libxcb.so.1: undefined symbol: xcb_xc_oisc_id`

**Comment by mkrasselt1** [comment]
it seams like ffmpeg has a problem - the same that causes im port image to fail, i will try to reinstall my octoprint on a clean sd card, lets check if that changes anything
