### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by b2kbutt** [fabianonline/OctoPrint-Telegram#98]
When trying to install via pluginmanager an error occurs. When using` ./pip install "https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip"` following errors are shown:

> Exception:
> Traceback (most recent call last)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
>     requirement_set.prepare_files(finder)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
>     session=self.session, hashes=hashes)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
>     hashes=hashes
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
>     hashes)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
>     _download_url(resp, link, content_file, hashes)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 603, in _download_url
>     hashes.check_against_chunks(downloaded_chunks)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
>     for chunk in chunks:
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
>     for chunk in chunks:
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
>     for x in it:
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
>     decode_content=False):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
>     data = self._fp.read(amt)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
>     self._close()
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
>     self.__callback(self.__buf.getvalue())
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
>     self.serializer.dumps(request, response, body=body),
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 55, in dumps
>     "body": _b64_encode_bytes(body),
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
>     return base64.b64encode(b).decode("ascii")
> MemoryError

**Comment by derpicknicker1** [comment]
Hm...i don't know whats going on. Have you managed to fix it?
